
export const START_LOADING="START_LOADING"
export const END_LOADING="END_LOADING"
export const SIGNUP="SIGNUP"
export const LOGIN="LOGIN"
export const LOGOUT="LOGOUT"
export const FETCH_USER="FETCH_USER"
export const CREATE="CREATE"
export const FETCH_ALL="FETCH_ALL"
export const FETCH="FETCH"
export const FETCH_BY_SEARCH="FETCH_BY_SEARCH"
export const UPDATE="UPDATE"
export const PAID="PAID"
export const UNPAID="UNPAID"
export const READ="READ"
export const DELETE="DELETE"

